//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace restMVC4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dish
    {
        public Dish()
        {
            this.Products = new HashSet<Products>();
            this.Order = new HashSet<Order>();
        }
    
        public int IdDish { get; set; }
        public int IdRestaurant { get; set; }
        public int IdCategory { get; set; }
        public string NameDish { get; set; }
        public string Weight { get; set; }
        public string Price { get; set; }
    
        public virtual CategoryProducts CategoryProducts { get; set; }
        public virtual Restaurants Restaurants { get; set; }
        public virtual ICollection<Products> Products { get; set; }
        public virtual ICollection<Order> Order { get; set; }
    }
}
