//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace restMVC4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public Order()
        {
            this.Basket = new HashSet<Basket>();
            this.Dish = new HashSet<Dish>();
        }
    
        public int IdOrder { get; set; }
        public int IdClient { get; set; }
        public System.DateTime DateOrder { get; set; }
        public System.DateTime DateDelivery { get; set; }
        public string AddressDelivery { get; set; }
        public string Payment { get; set; }
        public string Implementation { get; set; }
    
        public virtual ICollection<Basket> Basket { get; set; }
        public virtual Client Client { get; set; }
        public virtual ICollection<Dish> Dish { get; set; }
    }
}
