//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace restMVC4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products
    {
        public Products()
        {
            this.Dish = new HashSet<Dish>();
        }
    
        public int IdProducts { get; set; }
        public string NameProduct { get; set; }
        public string Weight { get; set; }
    
        public virtual ICollection<Dish> Dish { get; set; }
    }
}
